"""
Django settings for freewise project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os

from config.env import env, BASE_DIR # type: ignore

env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = ['*']

USER_AGENT = env('USER_AGENT')

# Application definition

INSTALLED_APPS = [

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'pages',

    'users', 'accounts',

    'freelancers', 'clients',

    'jobs', 'offers', 'contracts',

    'collabs',

    'payments',

    'notifications',

    'reviews',

]

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

WSGI_APPLICATION = 'config.wsgi.application'


AUTH_USER_MODEL = "users.user"
ACCOUNT_MODEL = "accounts.account"


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE':['profile', 'email'],

        'APP': {
            'client_id': env('SOCIALACCOUNT_PROVIDER_GOOGLE_ID'),
            'secret': env('SOCIALACCOUNT_PROVIDER_GOOGLE_SECRET'),
            'key': env('SOCIALACCOUNT_PROVIDER_GOOGLE_KEY'),
        },

        'AUTH_PARAMS': {
            'access_type': 'online',
        },

        'OAUTH_PKCE_ENABLED': True,
        'EMAIL_AUTHENTICATION': True,
        'EMAIL_AUTHENTICATION_AUTO_CONNECT': True,
    }
}




# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASSWORD'),
        'HOST': env('DATABASE_HOST'),
        'PORT': env('DATABASE_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Email Backend Configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"  # Or your email provider's SMTP host
EMAIL_PORT = 587  # Or your email provider's SMTP port (e.g., 465 for SSL)
EMAIL_USE_TLS = True  # Use TLS for secure connection
EMAIL_USE_SSL = False # Only set to True if your provider requires SSL and not TLS
EMAIL_HOST_USER = env('EMAIL_HOST_USER')  # email address
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD') # Use an app password for security, not your main email password
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')  # Default sender address for emails

# Session lifetime: 7 days (matches draft TTL)
SESSION_COOKIE_AGE = 7 * 24 * 60 * 60

# Sliding expiration: extend session on activity (good UX during multi-step checkout)
SESSION_SAVE_EVERY_REQUEST = True

# Do NOT expire at browser close — we want guests to come back via same device
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# SameSite protects against some CSRF/CSO issues; Lax is a good default for site flows
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Choose a session engine: cached_db is a good tradeoff (fast + persistent)
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

# Use JSON serializer (safer than pickle)
SESSION_SERIALIZER = "django.contrib.sessions.serializers.JSONSerializer"


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_LOCATION = "static"
STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'config/static'),
    os.path.join(BASE_DIR, 'assets'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles-cdn')

# media files (Images)
MEDIA_LOCATION = "media"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = "media/"

# DJANGO VITE
DJANGO_VITE = {
  "default": { "dev_mode": DEBUG }
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Assume most users will be local for now (Algeria), but store in international canonical form.
PHONENUMBER_DEFAULT_REGION = "DZ"   # local validation / examples for Algeria
PHONENUMBER_DB_FORMAT = "E164" # !!! DO DONT CHANGE THIS: visit docs for more details. store phone numbers in E.164 in DB (stable, recommended)
PHONENUMBER_DEFAULT_FORMAT = "NATIONAL"  # how phone numbers are formatted by default for display