"""
Django settings for freewise project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os

from config.env import env, BASE_DIR

from corsheaders.defaults import default_headers

env.read_env(os.path.join(BASE_DIR, '.env'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool('DJANGO_DEBUG', default=True)

ALLOWED_HOSTS = ['*']

USER_AGENT = env('USER_AGENT')

SITE_ID = 1

# Freewise specific settings
FREEWISE_PLATFORM_FEE_PERCENT = env.int("FREEWISE_PLATFORM_FEE_PERCENT", default=8)
FREEWISE_REVIEW_GRACE_DAYS = env.int("FREEWISE_REVIEW_GRACE_DAYS", default=7)

FREEWISE_PLATFORM_USERNAME = env("FREEWISE_PLATFORM_USERNAME")
FREEWISE_PLATFORM_EMAIL = env("FREEWISE_PLATFORM_EMAIL")

# Application definition

INSTALLED_APPS = [

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'allauth',
    'allauth.account',
    "allauth.headless",
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'phonenumber_field',

    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',

    # Freewise apps
    'pages',
    'users', 'accounts', 'freelancers', 'clients',
    'jobs', 'proposals', 'services', 'collabs',
    'notifications',
    'payments', 'contracts', 'reviews',
]

MIDDLEWARE = [

    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'config.urls'

WSGI_APPLICATION = 'config.wsgi.application'

FREEWISE_FRONTEND_URL = env("FREEWISE_FRONTEND_URL", default="http://localhost:3000")

AUTH_USER_MODEL = "users.user"
ACCOUNT_MODEL = "accounts.account"

ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_UNIQUE_EMAIL = True
HEADLESS_ONLY = True

ACCOUNT_EMAIL_CONFIRMATION_HMAC = True
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 1
ACCOUNT_EMAIL_VERIFICATION = "mandatory"

ACCOUNT_CONFIRM_EMAIL_ON_GET = False

HEADLESS_FRONTEND_URLS = {
    "account_confirm_email":
        "http://localhost:3000/auth/verify-email/{key}",

    "account_reset_password":
        "http://localhost:3000/auth/forgot-password",

    "account_reset_password_from_key":
        "http://localhost:3000/auth/reset-password/{key}",
}

ACCOUNT_RATE_LIMITS = {
    "confirm_email": "1/60s/key",
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE':['profile', 'email'],

        'APP': {
            'client_id': env('SOCIALACCOUNT_PROVIDER_GOOGLE_ID'),
            'secret': env('SOCIALACCOUNT_PROVIDER_GOOGLE_SECRET'),
            'key': env('SOCIALACCOUNT_PROVIDER_GOOGLE_KEY'),
        },

        'AUTH_PARAMS': {
            'access_type': 'online',
        },

        'OAUTH_PKCE_ENABLED': True,
        'EMAIL_AUTHENTICATION': True,
        'EMAIL_AUTHENTICATION_AUTO_CONNECT': True,
    }
}




# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASSWORD'),
        'HOST': env('DATABASE_HOST'),
        'PORT': env('DATABASE_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Email Backend Configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"  # Or your email provider's SMTP host
EMAIL_PORT = 587  # Or your email provider's SMTP port (e.g., 465 for SSL)
EMAIL_USE_TLS = True  # Use TLS for secure connection
EMAIL_USE_SSL = False # Only set to True if your provider requires SSL and not TLS
EMAIL_HOST_USER = env('EMAIL_HOST_USER')  # email address
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD') # Use an app password for security, not your main email password
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL')  # Default sender address for emails

# Session lifetime: 7 days (matches draft TTL)
SESSION_COOKIE_AGE = 7 * 24 * 60 * 60

# Sliding expiration: extend session on activity (good UX during multi-step checkout)
SESSION_SAVE_EVERY_REQUEST = True

# Do NOT expire at browser close — we want guests to come back via same device
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# SameSite protects against some CSRF/CSO issues; Lax is a good default for site flows
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"

# Choose a session engine: cached_db is a good tradeoff (fast + persistent)
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

# Use JSON serializer (safer than pickle)
SESSION_SERIALIZER = "django.contrib.sessions.serializers.JSONSerializer"


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_LOCATION = "static"
STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'config/static'),
    os.path.join(BASE_DIR, 'assets'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles-cdn')

# media files (Images)
MEDIA_LOCATION = "media"
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = "media/"

# DJANGO VITE
DJANGO_VITE = {
  "default": { "dev_mode": DEBUG }
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Assume most users will be local for now (Algeria), but store in international canonical form.
PHONENUMBER_DEFAULT_REGION = "DZ"   # local validation / examples for Algeria
PHONENUMBER_DB_FORMAT = "E164" # !!! DO DONT CHANGE THIS: visit docs for more details. store phone numbers in E.164 in DB (stable, recommended)
PHONENUMBER_DEFAULT_FORMAT = "NATIONAL"  # how phone numbers are formatted by default for display

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        "users.authentication.VersionedJWTAuthentication",
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
}

# SimpleJWT
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME':    timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME':   timedelta(days=7),
    'ROTATE_REFRESH_TOKENS':    True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES':        ('Bearer',),
}

# CORS
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.ngrok-free\.app$",
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOW_HEADERS = list(default_headers) + [
    "authorization",
]

# Chargily API keys
CHARGILY_PUBLIC_KEY = env('CHARGILY_PUBLIC_KEY')
CHARGILY_SECRET_KEY = env('CHARGILY_SECRET_KEY')

