# Generated by Django 4.2 on 2026-05-25 16:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowHold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated.', verbose_name='updated at')),
                ('idempotency_key', models.CharField(help_text='Unique key that prevents duplicate escrow holds.', max_length=120, unique=True, verbose_name='idempotency key')),
                ('contract_reference', models.CharField(help_text='Reference to the contract or order tied to this escrow hold.', max_length=100, verbose_name='contract reference')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount locked in escrow.', max_digits=14, verbose_name='amount')),
                ('currency', models.CharField(choices=[('DZD', 'Algerian Dinar'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='DZD', help_text='Currency used for this escrow hold.', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='active', help_text='Current state of the escrow hold.', max_length=20, verbose_name='status')),
                ('resolution_note', models.TextField(blank=True, default='', help_text='Internal note explaining why the escrow hold was resolved.', verbose_name='resolution note')),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the hold was released, refunded, disputed, or cancelled.', null=True, verbose_name='resolved at')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra contract or provider data stored as JSON.', verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'escrow hold',
                'verbose_name_plural': 'escrow holds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated.', verbose_name='updated at')),
                ('idempotency_key', models.CharField(help_text='Unique key that prevents duplicate payout requests.', max_length=120, unique=True, verbose_name='idempotency key')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount requested for payout.', max_digits=14, verbose_name='amount')),
                ('currency', models.CharField(choices=[('DZD', 'Algerian Dinar'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='DZD', help_text='Currency used for this payout.', max_length=3, verbose_name='currency')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('reversed', 'Reversed'), ('cancelled', 'Cancelled')], default='pending', help_text='Current payout processing state.', max_length=20, verbose_name='status')),
                ('provider_name', models.CharField(blank=True, default='', help_text='Provider handling this payout, if any.', max_length=50, verbose_name='provider name')),
                ('provider_reference', models.CharField(blank=True, default='', help_text='External payout reference from the provider.', max_length=255, verbose_name='provider reference')),
                ('destination_type', models.CharField(blank=True, default='', help_text='Type of payout destination such as bank account, phone, or wallet.', max_length=50, verbose_name='destination type')),
                ('destination_label', models.CharField(blank=True, default='', help_text='Human-readable payout destination label for admins and support.', max_length=255, verbose_name='destination label')),
                ('failure_reason', models.TextField(blank=True, default='', help_text='Why the payout failed, if it failed.', verbose_name='failure reason')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the payout was processed by the platform or provider.', null=True, verbose_name='processed at')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra payout data stored as JSON.', verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'payout',
                'verbose_name_plural': 'payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated.', verbose_name='updated at')),
                ('currency', models.CharField(choices=[('DZD', 'Algerian Dinar'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='DZD', help_text='ISO 4217 currency code used by this wallet. Freewise starts with DZD.', max_length=3, verbose_name='currency')),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Money the user can spend or withdraw right now.', max_digits=14, verbose_name='available balance')),
                ('escrow_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Money currently locked in contract escrow.', max_digits=14, verbose_name='escrow balance')),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen')], default='active', help_text='Wallet state. Frozen wallets should not be allowed to move funds.', max_length=20, verbose_name='status')),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated.', verbose_name='updated at')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('escrow_hold', 'Escrow hold'), ('escrow_release', 'Escrow release'), ('platform_fee', 'Platform fee'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal'), ('adjustment', 'Adjustment'), ('dispute_hold', 'Dispute hold')], help_text='Why this ledger entry exists.', max_length=30, verbose_name='transaction type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', help_text='Current processing state of this transaction.', max_length=20, verbose_name='status')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive amount moved by this transaction.', max_digits=14, verbose_name='amount')),
                ('currency', models.CharField(choices=[('DZD', 'Algerian Dinar'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='DZD', help_text='Currency used for this transaction.', max_length=3, verbose_name='currency')),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wallet balance before this transaction was applied.', max_digits=14, verbose_name='balance before')),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Wallet balance after this transaction was applied.', max_digits=14, verbose_name='balance after')),
                ('reference_type', models.CharField(blank=True, default='', help_text='Optional source object type such as contract, payout, or refund.', max_length=50, verbose_name='reference type')),
                ('reference_id', models.CharField(blank=True, default='', help_text='Optional source object identifier.', max_length=100, verbose_name='reference id')),
                ('provider_name', models.CharField(blank=True, default='', help_text='Payment provider name, if this transaction came from one.', max_length=50, verbose_name='provider name')),
                ('provider_reference', models.CharField(blank=True, default='', help_text='External reference from the payment provider.', max_length=255, verbose_name='provider reference')),
                ('idempotency_key', models.CharField(help_text='Unique key that prevents the same money action from being processed twice.', max_length=120, unique=True, verbose_name='idempotency key')),
                ('description', models.TextField(blank=True, default='', help_text='Human-readable explanation of this transaction.', verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra provider or business data stored as JSON.', verbose_name='metadata')),
            ],
            options={
                'verbose_name': 'wallet transaction',
                'verbose_name_plural': 'wallet transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this record was last updated.', verbose_name='updated at')),
                ('provider_name', models.CharField(default='chargily', help_text='Webhook provider name.', max_length=50, verbose_name='provider name')),
                ('event_name', models.CharField(help_text='Provider event name or type.', max_length=100, verbose_name='event name')),
                ('provider_event_id', models.CharField(blank=True, default='', help_text='Unique event identifier from the provider, if available.', max_length=255, verbose_name='provider event id')),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed'), ('ignored', 'Ignored')], default='received', help_text='Processing state of the webhook log.', max_length=20, verbose_name='status')),
                ('signature_valid', models.BooleanField(default=False, help_text='Whether the provider signature passed verification.', verbose_name='signature valid')),
                ('processed', models.BooleanField(default=False, help_text='Whether this webhook has already been handled successfully.', verbose_name='processed')),
                ('raw_body', models.TextField(help_text='Raw webhook payload exactly as received from the provider.', verbose_name='raw body')),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Parsed webhook payload stored as JSON.', verbose_name='payload')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Request headers captured at webhook time.', verbose_name='headers')),
                ('related_reference_type', models.CharField(blank=True, default='', help_text='Optional model type related to this webhook, such as payment or payout.', max_length=50, verbose_name='related reference type')),
                ('related_reference_id', models.CharField(blank=True, default='', help_text='Optional object identifier related to this webhook.', max_length=100, verbose_name='related reference id')),
                ('processing_error', models.TextField(blank=True, default='', help_text='Error message stored when webhook processing fails.', verbose_name='processing error')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When this webhook was processed.', null=True, verbose_name='processed at')),
            ],
            options={
                'verbose_name': 'webhook log',
                'verbose_name_plural': 'webhook logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['provider_name', 'event_name'], name='payments_we_provide_f3c186_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['provider_event_id'], name='payments_we_provide_7c117f_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['status'], name='payments_we_status_e00b78_idx'),
        ),
        migrations.AddIndex(
            model_name='webhooklog',
            index=models.Index(fields=['processed'], name='payments_we_process_5fc94e_idx'),
        ),
    ]
