# Generated by Django 4.2 on 2026-05-25 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='initiated_by',
            field=models.ForeignKey(blank=True, help_text='Who triggered the transaction. Leave empty for system actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_wallet_transactions', to=settings.AUTH_USER_MODEL, verbose_name='initiated by'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='wallet',
            field=models.ForeignKey(help_text='Wallet impacted by this transaction.', on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='payments.wallet', verbose_name='wallet'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(help_text='The account owner of this wallet.', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='payout',
            name='ledger_transaction',
            field=models.OneToOneField(blank=True, help_text='The wallet transaction that records this payout.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout', to='payments.wallettransaction', verbose_name='ledger transaction'),
        ),
        migrations.AddField(
            model_name='payout',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Who requested the payout. Leave empty for system actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_payouts', to=settings.AUTH_USER_MODEL, verbose_name='requested by'),
        ),
        migrations.AddField(
            model_name='payout',
            name='wallet',
            field=models.ForeignKey(help_text='Wallet this payout is paying out from.', on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to='payments.wallet', verbose_name='wallet'),
        ),
        migrations.AddField(
            model_name='escrowhold',
            name='funding_transaction',
            field=models.OneToOneField(help_text='The transaction that moved funds into escrow.', on_delete=django.db.models.deletion.PROTECT, related_name='escrow_hold_funding', to='payments.wallettransaction', verbose_name='funding transaction'),
        ),
        migrations.AddField(
            model_name='escrowhold',
            name='resolution_transaction',
            field=models.OneToOneField(blank=True, help_text='The transaction that released, refunded, or otherwise resolved this hold.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_hold_resolution', to='payments.wallettransaction', verbose_name='resolution transaction'),
        ),
        migrations.AddField(
            model_name='escrowhold',
            name='wallet',
            field=models.ForeignKey(help_text='Wallet from which the escrow funds were taken.', on_delete=django.db.models.deletion.PROTECT, related_name='escrow_holds', to='payments.wallet', verbose_name='wallet'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'transaction_type'], name='payments_wa_wallet__1a003d_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'status'], name='payments_wa_wallet__336b31_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['reference_type', 'reference_id'], name='payments_wa_referen_28f832_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['provider_name', 'provider_reference'], name='payments_wa_provide_68ad18_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['idempotency_key'], name='payments_wa_idempot_e0b4f9_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='payments_wa_user_id_cd1a1f_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['status'], name='payments_wa_status_0cb684_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['currency'], name='payments_wa_currenc_b00ee9_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['wallet', 'status'], name='payments_pa_wallet__3c6f19_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['provider_name', 'provider_reference'], name='payments_pa_provide_91eebd_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowhold',
            index=models.Index(fields=['wallet', 'status'], name='payments_es_wallet__539a1d_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowhold',
            index=models.Index(fields=['contract_reference'], name='payments_es_contrac_e14c73_idx'),
        ),
    ]
