# Generated by Django 4.2 on 2026-05-26 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='When the provider webhook successfully processed this payment.', null=True, verbose_name='processed at'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', help_text='Current processing state of this transaction.', max_length=20, verbose_name='status'),
        ),
    ]
