# Generated by Django 4.2 on 2026-05-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_wallettransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('escrow_hold', 'Escrow Hold'), ('escrow_release', 'Escrow Release'), ('payout', 'Payout'), ('refund', 'Refund'), ('platform_fee', 'Platform Fee'), ('adjustment', 'Adjustment')], help_text='Why this ledger entry exists.', max_length=30, verbose_name='transaction type'),
        ),
    ]
