# Generated by Django 4.2 on 2026-05-30 18:52

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_wallettransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escrowhold',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Remaining escrow amount. Zero is valid when the hold is fully resolved.', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='amount'),
        ),
    ]
