# Generated by Django 4.2 on 2026-06-02 19:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_remove_contract_disputed_at_contract_suspended_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0006_alter_escrowhold_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal unique ID for this payment attempt.', unique=True, verbose_name='attempt id')),
                ('provider', models.CharField(choices=[('chargily', 'Chargily')], db_index=True, default='chargily', help_text='Payment provider used for this attempt.', max_length=32, verbose_name='provider')),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, help_text='1 for the first try, 2 for the retry, and so on.', verbose_name='attempt number')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount requested from the client for this milestone.', max_digits=14, verbose_name='amount')),
                ('currency', models.CharField(help_text='Currency code used for this payment attempt.', max_length=3, verbose_name='currency')),
                ('internal_status', models.CharField(choices=[('CREATED', 'Created'), ('REDIRECTED', 'Redirected to provider'), ('PENDING_PROVIDER', 'Waiting for provider confirmation'), ('PROCESSING', 'Processing'), ('PAID_PROVIDER_NOT_SETTLED', 'Paid by provider, not settled yet'), ('SETTLED', 'Settled in Freewise'), ('FAILED', 'Failed'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired'), ('RECONCILED', 'Reconciled from provider status'), ('WEBHOOK_RECEIVED', 'Webhook received')], db_index=True, default='CREATED', help_text='Freewise payment state for this attempt.', max_length=40, verbose_name='internal status')),
                ('provider_status', models.CharField(blank=True, db_index=True, default='', help_text='Latest status reported by Chargily.', max_length=40, verbose_name='provider status')),
                ('provider_checkout_id', models.CharField(blank=True, db_index=True, default='', help_text='Chargily checkout ID returned when the attempt was created.', max_length=128, unique=True, verbose_name='provider checkout id')),
                ('provider_checkout_url', models.URLField(blank=True, default='', help_text='Hosted payment link returned by Chargily.', verbose_name='provider checkout url')),
                ('provider_payment_method', models.CharField(blank=True, default='', help_text='Payment method selected at the provider checkout.', max_length=32, verbose_name='provider payment method')),
                ('provider_reference', models.CharField(blank=True, db_index=True, default='', help_text='Any extra reference returned or echoed by the provider.', max_length=128, verbose_name='provider reference')),
                ('idempotency_key', models.CharField(db_index=True, help_text='Prevents duplicate attempts being created twice.', max_length=128, unique=True, verbose_name='idempotency key')),
                ('success_url', models.URLField(blank=True, default='', help_text='Success redirect URL used for this attempt.', verbose_name='success url')),
                ('failure_url', models.URLField(blank=True, default='', help_text='Failure redirect URL used for this attempt.', verbose_name='failure url')),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the checkout is expected to expire.', null=True, verbose_name='expires at')),
                ('provider_created_at', models.DateTimeField(blank=True, help_text='When the provider checkout was created.', null=True, verbose_name='provider created at')),
                ('provider_paid_at', models.DateTimeField(blank=True, help_text='When the provider marked the checkout as paid.', null=True, verbose_name='provider paid at')),
                ('webhook_received_at', models.DateTimeField(blank=True, help_text='When Freewise received a webhook for this attempt.', null=True, verbose_name='webhook received at')),
                ('webhook_processed_at', models.DateTimeField(blank=True, help_text='When the webhook was fully processed by Freewise.', null=True, verbose_name='webhook processed at')),
                ('reconciled_at', models.DateTimeField(blank=True, help_text='When Freewise reconciled this attempt from provider status.', null=True, verbose_name='reconciled at')),
                ('last_reconciled_at', models.DateTimeField(blank=True, help_text='When Freewise last tried to reconcile this attempt from provider status.', null=True, verbose_name='last reconciled at')),
                ('settled_at', models.DateTimeField(blank=True, help_text='When Freewise finalized the money flow from this attempt.', null=True, verbose_name='settled at')),
                ('failure_reason', models.TextField(blank=True, default='', help_text='Human-readable reason why the attempt failed.', verbose_name='failure reason')),
                ('webhook_payload', models.JSONField(blank=True, default=dict, help_text='Raw webhook payload received from the provider.', verbose_name='webhook payload')),
                ('provider_snapshot', models.JSONField(blank=True, default=dict, help_text='Latest provider checkout snapshot stored by Freewise.', verbose_name='provider snapshot')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this payment attempt was created.', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this payment attempt was last updated.', verbose_name='updated at')),
                ('contract', models.ForeignKey(help_text='Contract this payment attempt belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='contracts.contract', verbose_name='contract')),
                ('escrow_hold', models.OneToOneField(blank=True, help_text='Escrow hold created after the payment was settled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_attempt', to='payments.escrowhold', verbose_name='escrow hold')),
                ('initiated_by', models.ForeignKey(blank=True, help_text='User who started this payment attempt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_payment_attempts', to=settings.AUTH_USER_MODEL, verbose_name='initiated by')),
                ('milestone', models.ForeignKey(help_text='Milestone being funded by this payment attempt.', on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='contracts.milestone', verbose_name='milestone')),
                ('retry_of', models.ForeignKey(blank=True, help_text='Previous payment attempt that this one retried.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='payments.paymentattempt', verbose_name='retry of')),
                ('settlement_transaction', models.OneToOneField(blank=True, help_text='Wallet transaction created when the attempt was settled.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_attempt', to='payments.wallettransaction', verbose_name='settlement transaction')),
            ],
            options={
                'verbose_name': 'payment attempt',
                'verbose_name_plural': 'payment attempts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['contract', 'milestone'], name='payments_pa_contrac_2f4881_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['provider', 'provider_status'], name='payments_pa_provide_178263_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['internal_status'], name='payments_pa_interna_a4f1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['idempotency_key'], name='payments_pa_idempot_57d1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['provider_checkout_id'], name='payments_pa_provide_f795ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('milestone', 'attempt_number'), name='unique_payment_attempt_number_per_milestone'),
        ),
    ]
