# Generated by Django 4.2 on 2026-06-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentattempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentattempt',
            name='provider_checkout_id',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Chargily or gateway checkout ID returned after checkout creation.', max_length=128, null=True, unique=True, verbose_name='provider checkout id'),
        ),
    ]
