# Generated by Django 4.2 on 2026-05-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular User'), ('platform', 'Platform Account')], default='regular', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('type', 'platform')), fields=('type',), name='unique_platform_user'),
        ),
    ]
