# Generated by Django 4.2 on 2026-05-07 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_merchant',
        ),
    ]
