# Generated by Django 4.2 on 2026-05-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_token_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_version',
            field=models.PositiveIntegerField(default=0, help_text='Used to invalidate existing JWT sessions. Incrementing this value revokes all previously issued access and refresh tokens for the user.'),
        ),
    ]
