# Generated by Django 4.2 on 2026-05-26 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freelancers', '0001_initial'),
        ('clients', '0001_initial'),
        ('proposals', '0001_initial'),
        ('jobs', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['-created_at'], 'verbose_name': 'contract', 'verbose_name_plural': 'contracts'},
        ),
        migrations.AlterModelOptions(
            name='milestone',
            options={'ordering': ['order', 'created_at'], 'verbose_name': 'milestone', 'verbose_name_plural': 'milestones'},
        ),
        migrations.AddField(
            model_name='contract',
            name='active_at',
            field=models.DateTimeField(blank=True, help_text='When the work officially started.', null=True, verbose_name='active at'),
        ),
        migrations.AddField(
            model_name='contract',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the contract was cancelled.', null=True, verbose_name='cancelled at'),
        ),
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(default='DZD', help_text='Contract currency code. Freewise starts with DZD.', max_length=3, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='contract',
            name='disputed_at',
            field=models.DateTimeField(blank=True, help_text='When the contract entered dispute.', null=True, verbose_name='disputed at'),
        ),
        migrations.AddField(
            model_name='contract',
            name='funded_at',
            field=models.DateTimeField(blank=True, help_text='When the contract was funded into escrow.', null=True, verbose_name='funded at'),
        ),
        migrations.AddField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Internal notes or summary for moderators and admins.', verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='contract',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='When escrow was refunded.', null=True, verbose_name='refunded at'),
        ),
        migrations.AddField(
            model_name='contract',
            name='released_at',
            field=models.DateTimeField(blank=True, help_text='When escrow was fully released.', null=True, verbose_name='released at'),
        ),
        migrations.AddField(
            model_name='contract',
            name='source_type',
            field=models.CharField(choices=[('job_board', 'Job board'), ('service_order', 'Service order')], db_index=True, default='job_board', help_text='Where this contract came from.', max_length=20, verbose_name='source type'),
        ),
        migrations.AddField(
            model_name='contract',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the first milestone or final work was submitted.', null=True, verbose_name='submitted at'),
        ),
        migrations.AddField(
            model_name='contract',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Short human-readable contract title.', max_length=255, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='currency',
            field=models.CharField(default='DZD', help_text='Milestone currency code.', max_length=3, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional milestone description.', verbose_name='description'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='dispute_reason',
            field=models.TextField(blank=True, default='', help_text='Reason the milestone was disputed.', verbose_name='dispute reason'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='disputed_at',
            field=models.DateTimeField(blank=True, help_text='When this milestone entered dispute.', null=True, verbose_name='disputed at'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='When this milestone was refunded.', null=True, verbose_name='refunded at'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='released_at',
            field=models.DateTimeField(blank=True, help_text='When escrow was released for this milestone.', null=True, verbose_name='released at'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='review_note',
            field=models.TextField(blank=True, default='', help_text='Optional note from the client after review.', verbose_name='review note'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='submission_note',
            field=models.TextField(blank=True, default='', help_text='Optional note from the freelancer when submitting work.', verbose_name='submission note'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this milestone was last updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, help_text='Total agreed amount for the contract.', max_digits=14, verbose_name='agreed price'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(help_text='The client side of the contract.', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='clients.clientprofile', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the contract fully completed and funds were released or refunded.', null=True, verbose_name='completed at'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this contract was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deadline',
            field=models.DateField(help_text='Delivery deadline agreed by both parties.', verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='freelancer',
            field=models.ForeignKey(help_text='The freelancer side of the contract.', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='freelancers.freelancerprofile', verbose_name='freelancer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='job',
            field=models.OneToOneField(blank=True, help_text='Linked job post, if the contract came from the job board.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='jobs.job', verbose_name='job'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='proposal',
            field=models.OneToOneField(blank=True, help_text='Linked proposal, if the contract came from a proposal.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='proposals.proposal', verbose_name='proposal'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_funding', 'Pending funding'), ('funded', 'Funded'), ('active', 'Active'), ('submitted', 'Submitted'), ('revision_requested', 'Revision requested'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('released', 'Released'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='draft', help_text='Current lifecycle state of the contract.', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='When this contract was last updated.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Milestone amount.', max_digits=14, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the client approved this milestone.', null=True, verbose_name='approved at'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='contract',
            field=models.ForeignKey(help_text='Parent contract for this milestone.', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract', verbose_name='contract'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this milestone was created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(help_text='Expected delivery date for this milestone.', verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='Used to sort milestones in sequence.', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('funded', 'Funded'), ('submitted', 'Submitted'), ('revision_requested', 'Revision requested'), ('approved', 'Approved'), ('disputed', 'Disputed'), ('released', 'Released'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current lifecycle state of the milestone.', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the freelancer submitted this milestone.', null=True, verbose_name='submitted at'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='title',
            field=models.CharField(help_text='Short milestone title.', max_length=255, verbose_name='title'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='contracts_c_status_aa7a80_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['source_type'], name='contracts_c_source__9b4681_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['client'], name='contracts_c_client__6ebd28_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['freelancer'], name='contracts_c_freelan_eda242_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['contract', 'status'], name='contracts_m_contrac_f0c342_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['order'], name='contracts_m_order_6a90fa_idx'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.UniqueConstraint(fields=('contract', 'order'), name='unique_milestone_order_per_contract'),
        ),
    ]
