# Generated by Django 4.2 on 2026-05-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_alter_contract_options_alter_milestone_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='source_type',
            field=models.CharField(choices=[('JOB_BOARD', 'Job board'), ('SERVICE_ORDER', 'Service order')], db_index=True, default='JOB_BOARD', help_text='Where this contract came from.', max_length=20, verbose_name='source type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_FUNDING', 'Pending funding'), ('FUNDED', 'Funded'), ('ACTIVE', 'Active'), ('SUBMITTED', 'Submitted'), ('REVISION_REQUESTED', 'Revision requested'), ('APPROVED', 'Approved'), ('DISPUTED', 'Disputed'), ('RELEASED', 'Released'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], db_index=True, default='DRAFT', help_text='Current lifecycle state of the contract.', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FUNDED', 'Funded'), ('SUBMITTED', 'Submitted'), ('REVISION_REQUESTED', 'Revision requested'), ('APPROVED', 'Approved'), ('DISPUTED', 'Disputed'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', help_text='Current lifecycle state of the milestone.', max_length=30, verbose_name='status'),
        ),
    ]
