# Generated by Django 4.2 on 2026-05-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_source_type_alter_contract_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='submission_link',
            field=models.URLField(blank=True, default='', help_text='Optional link to the delivered work, preview, or files.', verbose_name='submission link'),
        ),
    ]
