# Generated by Django 4.2 on 2026-05-30 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0004_milestone_submission_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='resolution_note',
            field=models.TextField(blank=True, default='', help_text='Optional note from the client after resolution.', verbose_name='resolution note'),
        ),
        migrations.CreateModel(
            name='ContractEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CONTRACT_CREATED', 'Contract created'), ('MILESTONE_CREATED', 'Milestone created'), ('MILESTONE_FUNDED', 'Milestone funded'), ('MILESTONE_SUBMITTED', 'Milestone submitted'), ('MILESTONE_APPROVED', 'Milestone approved'), ('MILESTONE_REVISION_REQUESTED', 'Milestone revision requested'), ('MILESTONE_DISPUTED', 'Milestone disputed'), ('MILESTONE_RELEASED', 'Milestone released'), ('MILESTONE_REFUNDED', 'Milestone refunded'), ('MILESTONE_DISPUTE_RESOLVED_TO_CLIENT', 'Milestone dispute resolved to client'), ('MILESTONE_DISPUTE_RESOLVED_TO_FREELANCER', 'Milestone dispute resolved to freelancer'), ('CONTRACT_FUNDED', 'Contract funded'), ('CONTRACT_CANCELLED', 'Contract cancelled'), ('CONTRACT_DISPUTED', 'Contract disputed'), ('CONTRACT_RELEASED', 'Contract released'), ('CONTRACT_REFUNDED', 'Contract refunded')], max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contracts.contract')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contractevent',
            index=models.Index(fields=['contract', 'event_type'], name='contracts_c_contrac_972b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='contractevent',
            index=models.Index(fields=['-created_at'], name='contracts_c_created_df358d_idx'),
        ),
    ]
