# Generated by Django 4.2 on 2026-05-30 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_milestone_resolution_note_contractevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='revision_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the client requested this revision.', null=True, verbose_name='revision requested at'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='revision_scope',
            field=models.TextField(blank=True, default='', help_text='What exactly needs to change before resubmission.', verbose_name='revision scope'),
        ),
        migrations.AlterField(
            model_name='contractevent',
            name='event_type',
            field=models.CharField(choices=[('CONTRACT_CREATED', 'Contract created'), ('MILESTONE_CREATED', 'Milestone created'), ('MILESTONE_FUNDED', 'Milestone funded'), ('MILESTONE_SUBMITTED', 'Milestone submitted'), ('MILESTONE_APPROVED', 'Milestone approved'), ('MILESTONE_REVISION_REQUESTED', 'Milestone revision requested'), ('MILESTONE_REJECTED', 'Milestone rejected'), ('MILESTONE_REVISED', 'Milestone revised'), ('MILESTONE_DISPUTED', 'Milestone disputed'), ('MILESTONE_RELEASED', 'Milestone released'), ('MILESTONE_REFUNDED', 'Milestone refunded'), ('MILESTONE_DISPUTE_RESOLVED_TO_CLIENT', 'Milestone dispute resolved to client'), ('MILESTONE_DISPUTE_RESOLVED_TO_FREELANCER', 'Milestone dispute resolved to freelancer'), ('CONTRACT_FUNDED', 'Contract funded'), ('CONTRACT_CANCELLED', 'Contract cancelled'), ('CONTRACT_DISPUTED', 'Contract disputed'), ('CONTRACT_RELEASED', 'Contract released'), ('CONTRACT_REFUNDED', 'Contract refunded')], max_length=64),
        ),
    ]
