# Generated by Django 4.2 on 2026-05-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_milestone_revision_requested_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_FUNDING', 'Pending funding'), ('IN_PROGRESS', 'In progress'), ('DISPUTED', 'Disputed'), ('COMPLETED', 'Completed'), ('REFUNDED', 'Refunded'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', help_text='Current lifecycle state of the contract.', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FUNDED', 'Funded'), ('SUBMITTED', 'Submitted'), ('REVISION_REQUESTED', 'Revision requested'), ('DISPUTED', 'Disputed'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', help_text='Current lifecycle state of the milestone.', max_length=30, verbose_name='status'),
        ),
    ]
