# Generated by Django 4.2 on 2026-05-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0007_alter_contract_status_alter_milestone_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='funded_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='refunded_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='released_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='milestone',
            name='funded_at',
            field=models.DateTimeField(blank=True, help_text='When this milestone was funded into escrow.', null=True, verbose_name='funded at'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='review_due_at',
            field=models.DateTimeField(blank=True, help_text='When the milestone can be auto-finalized if the client does nothing.', null=True, verbose_name='review due at'),
        ),
    ]
