# Generated by Django 4.2 on 2026-06-01 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freelancers', '0001_initial'),
        ('clients', '0001_initial'),
        ('proposals', '0001_initial'),
        ('jobs', '0001_initial'),
        ('contracts', '0008_remove_contract_funded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='disputed_at',
        ),
        migrations.AddField(
            model_name='contract',
            name='suspended_at',
            field=models.DateTimeField(blank=True, help_text='When the contract was paused because of a dispute or review.', null=True, verbose_name='suspended at'),
        ),
        migrations.AddField(
            model_name='contract',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, help_text='When the contract ended early after work had started.', null=True, verbose_name='withdrawn at'),
        ),
        migrations.AddField(
            model_name='contractevent',
            name='message',
            field=models.TextField(blank=True, default='', help_text='Optional human-readable note about this event.', verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='active_at',
            field=models.DateTimeField(blank=True, help_text='When the contract moved into active work.', null=True, verbose_name='active at'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, help_text='The full amount the client and freelancer agreed on.', max_digits=14, verbose_name='agreed price'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When the contract was stopped before it started.', null=True, verbose_name='cancelled at'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(help_text='The client on this contract.', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='clients.clientprofile', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When the contract fully finished.', null=True, verbose_name='completed at'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currency',
            field=models.CharField(default='DZD', help_text='Three-letter currency code used for this contract.', max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='deadline',
            field=models.DateField(help_text='The final delivery date both parties agreed to.', verbose_name='deadline'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='freelancer',
            field=models.ForeignKey(help_text='The freelancer on this contract.', on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='freelancers.freelancerprofile', verbose_name='freelancer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='job',
            field=models.OneToOneField(blank=True, help_text='Linked job post, if this contract came from the job board.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='jobs.job', verbose_name='job'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Private notes for support or moderation.', verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='proposal',
            field=models.OneToOneField(blank=True, help_text='Accepted proposal for this contract, if any.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='proposals.proposal', verbose_name='proposal'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='source_type',
            field=models.CharField(choices=[('JOB_BOARD', 'Job board'), ('SERVICE_ORDER', 'Service order')], db_index=True, default='JOB_BOARD', help_text='Where this contract started.', max_length=20, verbose_name='source type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_FUNDING', 'Pending funding'), ('IN_PROGRESS', 'In progress'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', help_text='The overall stage of the contract.', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(blank=True, default='', help_text='Short title shown in the dashboard.', max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='contractevent',
            name='actor',
            field=models.ForeignKey(blank=True, help_text='The user who triggered this event, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='actor'),
        ),
        migrations.AlterField(
            model_name='contractevent',
            name='contract',
            field=models.ForeignKey(help_text='The contract this activity belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contracts.contract', verbose_name='contract'),
        ),
        migrations.AlterField(
            model_name='contractevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When this event was recorded.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='contractevent',
            name='event_type',
            field=models.CharField(choices=[('CONTRACT_CREATED', 'Contract created'), ('CONTRACT_FUNDED', 'Contract funded'), ('CONTRACT_SUSPENDED', 'Contract suspended'), ('CONTRACT_WITHDRAWN', 'Contract withdrawn'), ('CONTRACT_CANCELLED', 'Contract cancelled'), ('CONTRACT_COMPLETED', 'Contract completed'), ('MILESTONE_CREATED', 'Milestone created'), ('MILESTONE_FUNDED', 'Milestone funded'), ('MILESTONE_SUBMITTED', 'Milestone submitted'), ('MILESTONE_REVISION_REQUESTED', 'Milestone revision requested'), ('MILESTONE_REJECTED', 'Milestone rejected'), ('MILESTONE_REVISED', 'Milestone revised'), ('MILESTONE_DISPUTED', 'Milestone disputed'), ('MILESTONE_APPROVED', 'Milestone approved'), ('MILESTONE_RELEASED', 'Milestone released'), ('MILESTONE_REFUNDED', 'Milestone refunded'), ('MILESTONE_DISPUTE_RESOLVED_TO_CLIENT', 'Milestone dispute resolved to client'), ('MILESTONE_DISPUTE_RESOLVED_TO_FREELANCER', 'Milestone dispute resolved to freelancer')], help_text='What happened in the contract timeline.', max_length=64, verbose_name='event type'),
        ),
        migrations.AlterField(
            model_name='contractevent',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra structured details for the event timeline.', verbose_name='metadata'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='The amount reserved for this milestone.', max_digits=14, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='When the client approved the submission.', null=True, verbose_name='approved at'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='contract',
            field=models.ForeignKey(help_text='The contract this milestone belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract', verbose_name='contract'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='currency',
            field=models.CharField(default='DZD', help_text='Three-letter currency code used for this milestone.', max_length=3, verbose_name='currency'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional details about this milestone.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='dispute_reason',
            field=models.TextField(blank=True, default='', help_text='Why the milestone was disputed.', verbose_name='dispute reason'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='disputed_at',
            field=models.DateTimeField(blank=True, help_text='When this milestone was marked as disputed.', null=True, verbose_name='disputed at'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='due_date',
            field=models.DateField(help_text='The expected delivery date for this milestone.', verbose_name='due date'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='funded_at',
            field=models.DateTimeField(blank=True, help_text='When money was locked in escrow for this milestone.', null=True, verbose_name='funded at'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='order',
            field=models.PositiveSmallIntegerField(default=1, help_text='The order this milestone appears in.', verbose_name='order'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='When this milestone was refunded back to the client.', null=True, verbose_name='refunded at'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='resolution_note',
            field=models.TextField(blank=True, default='', help_text='A note about how the dispute was resolved.', verbose_name='resolution note'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='review_due_at',
            field=models.DateTimeField(blank=True, help_text='When the review window ends and Freewise may auto-finalize the milestone.', null=True, verbose_name='review due at'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='review_note',
            field=models.TextField(blank=True, default='', help_text='A note from the client after review.', verbose_name='review note'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='revision_requested_at',
            field=models.DateTimeField(blank=True, help_text='When the client asked for a revision.', null=True, verbose_name='revision requested at'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='revision_scope',
            field=models.TextField(blank=True, default='', help_text='What should change before the freelancer resubmits.', verbose_name='revision scope'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FUNDED', 'Funded'), ('SUBMITTED', 'Submitted'), ('REVISION_REQUESTED', 'Revision requested'), ('DISPUTED', 'Disputed'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded')], db_index=True, default='PENDING', help_text='The current stage of this milestone.', max_length=30, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='submission_link',
            field=models.URLField(blank=True, default='', help_text='A link to the delivered work, preview, or files.', verbose_name='submission link'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='submission_note',
            field=models.TextField(blank=True, default='', help_text='A short note from the freelancer when submitting work.', verbose_name='submission note'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='title',
            field=models.CharField(help_text='A short milestone title.', max_length=255, verbose_name='title'),
        ),
    ]
