# Generated by Django 4.2 on 2026-06-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0009_remove_contract_disputed_at_contract_suspended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='public_id',
            field=models.CharField(db_index=True, default=1, editable=False, help_text='Public contract ID used in URLs and sharing.', max_length=16, verbose_name='public id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milestone',
            name='public_id',
            field=models.CharField(db_index=True, default=1, editable=False, help_text='Public milestone ID used in URLs and sharing.', max_length=16, verbose_name='public id'),
            preserve_default=False,
        ),
    ]
