# Generated by Django 4.2 on 2026-06-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0011_alter_contract_public_id_alter_milestone_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, help_text='Public contract ID used in URLs and sharing.', max_length=16, null=True, verbose_name='public id'),
        ),
        migrations.AlterField(
            model_name='milestone',
            name='public_id',
            field=models.CharField(blank=True, db_index=True, help_text='Public milestone ID used in URLs and sharing.', max_length=16, null=True, verbose_name='public id'),
        ),
    ]
