# Generated by Django 4.2 on 2026-06-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0012_alter_contract_public_id_alter_milestone_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='public_id',
            field=models.CharField(db_index=True, default=1, editable=False, help_text='Public contract ID used in URLs and sharing.', max_length=16, unique=True, verbose_name='public id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='milestone',
            name='public_id',
            field=models.CharField(db_index=True, default=1, editable=False, help_text='Public milestone ID used in URLs and sharing.', max_length=16, unique=True, verbose_name='public id'),
            preserve_default=False,
        ),
    ]
