# Generated by Django 4.2 on 2025-12-01 19:47

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('locale', models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic'), ('FR', 'French')], default='EN', max_length=255)),
                ('theme', models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark'), ('DEVICE', 'Device')], default='DEVICE', max_length=255)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
