# Generated by Django 4.2 on 2026-05-22 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_email_verified_account_phone_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email_verified',
        ),
    ]
