# Generated by Django 4.2 on 2026-05-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/avatars/'),
        ),
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='locale',
            field=models.CharField(choices=[('EN', 'English'), ('AR', 'Arabic'), ('FR', 'French')], default='EN', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='theme',
            field=models.CharField(choices=[('LIGHT', 'Light'), ('DARK', 'Dark'), ('DEVICE', 'Device')], default='DEVICE', max_length=10),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
