# Generated by Django 4.2 on 2026-05-11 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('freelancers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollabPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('spots', models.PositiveSmallIntegerField(default=1, help_text='How many collaborators are needed')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_posts', to='freelancers.freelancerprofile')),
                ('skills_needed', models.ManyToManyField(blank=True, related_name='collab_posts', to='freelancers.skill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollabMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_description', models.CharField(blank=True, max_length=200)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('collab_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='collabs.collabpost')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_memberships', to='freelancers.freelancerprofile')),
            ],
            options={
                'unique_together': {('collab_post', 'freelancer')},
            },
        ),
        migrations.CreateModel(
            name='CollabApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collab_applications', to='freelancers.freelancerprofile')),
                ('collab_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='collabs.collabpost')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('collab_post', 'applicant')},
            },
        ),
    ]
