# Generated by Django 4.2 on 2026-05-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_avatar_account_birthday_account_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('JOB_NEW_OFFER', 'New offer on your job'), ('OFFER_ACCEPTED', 'Your offer was accepted'), ('OFFER_REJECTED', 'Your offer was rejected'), ('CONTRACT_STARTED', 'Contract started'), ('PAYMENT_HELD', 'Payment is in escrow'), ('MILESTONE_SUBMITTED', 'Milestone submitted for review'), ('MILESTONE_APPROVED', 'Milestone approved'), ('PAYOUT_SENT', 'Payout has been sent'), ('DISPUTE_OPENED', 'A dispute was opened'), ('DISPUTE_RESOLVED', 'Dispute resolved'), ('COLLAB_APPLICATION', 'New collab application'), ('COLLAB_ACCEPTED', 'Collab application accepted'), ('REVIEW_RECEIVED', 'You received a review'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
